spring:
  application:
    name: pinshot
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: 83bab50a30280e9adb3ee76d1dde0be90d40d700bfdc71829c09f5134fa6b0cd9d37fd73c3189d8d2f4ec3f0f44311b816ceee1f834a5eb3710a3235a7bc9d3b

coolsms:
  api-key: NCSV5GKYWM1EQR4O
  secret-key: OSUTCNMMFOFAXX8IKS17DCPDOYVQVWDN
  sms-provider: https://api.coolsms.co.kr
  sms-sender: 01073998508